name: Test Project
on:
  push:
    branches:
      - 'nestjs_v11'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
